/* ibus-immodule-1.0.vapi generated by vapigen-0.56, do not modify. */

[CCode (cprefix = "IBus", gir_namespace = "IBusIMModule", gir_version = "1.0", lower_case_cprefix = "ibus_")]
namespace IBusIMModule {
	[CCode (cheader_filename = "ibusimmodule.h")]
	public static string? im_module_get_id ([CCode (array_length_cname = "argc", array_length_pos = 0.5)] string[] argv);
}
